import React from 'react';

export default function AiQualityAuditModal({ isOpen, onClose, evaluation, modelName }) {
  if (!isOpen || !evaluation) return null;

  const {
    trust_score = 0,
    faithfulness_score = 0,
    coverage_score = 0,
    risk_level = 'Zero Hallucination',
    confidence_tag = 'Scientifically Verified',
    total_claims_audited = 0,
    verified_claims_count = 0,
    audit_trail = [],
    ground_truth_sample = {}
  } = evaluation;

  const discrepancyCount = audit_trail.filter(a => a.status === 'DISCREPANCY').length;
  const plausibleCount = audit_trail.filter(a => a.status === 'PLAUSIBLE').length;

  const getScoreColor = (score) => {
    if (score >= 85) return 'var(--success-color, #10b981)';
    if (score >= 70) return 'var(--warning-color, #f59e0b)';
    return 'var(--danger-color, #ef4444)';
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'VERIFIED':
        return <span className="audit-badge verified">✓ Ground Truth Verified</span>;
      case 'PLAUSIBLE':
        return <span className="audit-badge plausible">≈ Plausible / Ratio</span>;
      case 'DISCREPANCY':
        return <span className="audit-badge discrepancy">✕ Discrepancy</span>;
      default:
        return <span className="audit-badge neutral">{status}</span>;
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-content audit-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div>
            <div className="audit-title-row">
              <h3>AI Factual Grounding & Evaluation Audit</h3>
              <span className="model-pill">{modelName || 'Local AI Model'}</span>
            </div>
            <p className="modal-subtitle">
              Every numerical statement generated by the AI is cross-audited against SQLite ground truth.
            </p>
          </div>
          <button className="btn-close" onClick={onClose} aria-label="Close modal">×</button>
        </div>

        <div className="audit-kpi-row">
          <div className="audit-kpi-card" style={{ borderColor: getScoreColor(trust_score) }}>
            <div className="audit-kpi-value" style={{ color: getScoreColor(trust_score) }}>
              {trust_score}%
            </div>
            <div className="audit-kpi-label">Overall Trust Score</div>
          </div>
          <div className="audit-kpi-card">
            <div className="audit-kpi-value">{faithfulness_score}%</div>
            <div className="audit-kpi-label">Faithfulness Score</div>
          </div>
          <div className="audit-kpi-card">
            <div className="audit-kpi-value">{coverage_score}%</div>
            <div className="audit-kpi-label">Factual Coverage</div>
          </div>
          <div className="audit-kpi-card">
            <div className="audit-kpi-value" style={{ color: discrepancyCount > 0 ? 'var(--danger-color, #ef4444)' : 'var(--success-color, #10b981)' }}>
              {verified_claims_count} / {total_claims_audited}
            </div>
            <div className="audit-kpi-label">Verified Claims ({discrepancyCount} flags)</div>
          </div>
        </div>

        <div className="audit-summary-bar">
          <strong>Evaluation Confidence:</strong> {confidence_tag} · <em>{risk_level}</em>
        </div>

        <div className="audit-table-wrap">
          <table className="audit-table">
            <thead>
              <tr>
                <th style={{ width: '42%' }}>AI Narrative Claim</th>
                <th style={{ width: '12%' }}>Claimed</th>
                <th style={{ width: '18%' }}>Database Ground Truth</th>
                <th style={{ width: '16%' }}>Audit Status</th>
                <th style={{ width: '12%' }}>Target Metric</th>
              </tr>
            </thead>
            <tbody>
              {audit_trail.length === 0 ? (
                <tr>
                  <td colSpan="5" style={{ textAlign: 'center', padding: '24px' }}>
                    No numerical claims detected in this story.
                  </td>
                </tr>
              ) : (
                audit_trail.map((claim, idx) => (
                  <tr key={idx} className={`audit-row-${claim.status ? claim.status.toLowerCase() : 'neutral'}`}>
                    <td className="claim-text">"{claim.claim_text}"</td>
                    <td className="claim-extracted">
                      <code>{claim.claim_value != null ? claim.claim_value : '—'}</code>
                    </td>
                    <td className="claim-expected">
                      {claim.database_value != null ? (
                        <div>
                          <code>{claim.database_value}</code>
                        </div>
                      ) : (
                        <span className="text-muted">Contextual / Proportional</span>
                      )}
                    </td>
                    <td>{getStatusBadge(claim.status)}</td>
                    <td className="claim-rationale"><small>{claim.database_target}</small></td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="modal-footer">
          <span className="text-muted">
            Audited deterministically using SQLite dataset profiling and mathematical verification bounds.
          </span>
          <button className="btn-secondary" onClick={onClose}>Close Audit</button>
        </div>
      </div>
    </div>
  );
}
