import io
import pandas as pd
import pytest
from pathlib import Path

from app.services.sheet_catalog import read_sheets, numeric_values, sniff_delimiter_and_header


def test_sniff_delimiter_and_header():
    # Semicolon CSV
    semi_csv = "Name;Age;Salary\nAlice;30;75000\nBob;40;95000\n"
    sep, skip = sniff_delimiter_and_header(semi_csv)
    assert sep == ";"
    assert skip == 0

    # Tab TSV
    tab_tsv = "Name\tDepartment\tRating\nCharlie\tFinance\t4.5\nDana\tTech\t4.9\n"
    sep, skip = sniff_delimiter_and_header(tab_tsv, default_sep="\t")
    assert sep == "\t"
    assert skip == 0

    # Preamble metadata rows before header
    preamble_csv = "Report: Executive Headcount\nExported: 2026-10-01\nEmpID,Name,Dept\n101,Eve,Sales\n102,Frank,HR\n"
    sep, skip = sniff_delimiter_and_header(preamble_csv)
    assert sep == ","
    assert skip == 2


def test_read_sheets_semicolon_and_tsv(tmp_path):
    # Test semicolon file
    semi_path = tmp_path / "euro_data.csv"
    semi_path.write_text("Product;Category;Price\nLaptop;Tech;1200\nDesk;Office;350\n", encoding="utf-8")
    frames = read_sheets(semi_path)
    assert "Sheet1" in frames
    df = frames["Sheet1"]
    assert list(df.columns) == ["Product", "Category", "Price"]
    assert len(df) == 2
    assert df.iloc[0]["Price"] == "1200"

    # Test tab-separated TSV file
    tsv_path = tmp_path / "roster.tsv"
    tsv_path.write_text("Employee ID\tName\tRole\n001\tGrace\tEngineer\n002\tHeidi\tManager\n", encoding="utf-8")
    frames_tsv = read_sheets(tsv_path)
    assert "Sheet1" in frames_tsv
    df_tsv = frames_tsv["Sheet1"]
    assert list(df_tsv.columns) == ["Employee ID", "Name", "Role"]
    assert len(df_tsv) == 2
    assert df_tsv.iloc[0]["Employee ID"] == "001"


def test_read_sheets_with_preamble(tmp_path):
    preamble_path = tmp_path / "adp_export.csv"
    preamble_path.write_text(
        "CONFIDENTIAL HR REPORT - GENERATED BY SYSTEM\n"
        "RUN DATE: 2026-09-30\n"
        "ID,Employee,Division,Performance\n"
        "E1,Ian,Engineering,High\n"
        "E2,Judy,Design,Medium\n",
        encoding="utf-8"
    )
    frames = read_sheets(preamble_path)
    assert "Sheet1" in frames
    df = frames["Sheet1"]
    assert list(df.columns) == ["ID", "Employee", "Division", "Performance"]
    assert len(df) == 2
    assert df.iloc[0]["Employee"] == "Ian"


def test_numeric_values_currencies_and_thousands():
    # Currencies with thousands commas
    s_curr = pd.Series(["$1,250.50", "$3,400.00", "$950.00"])
    num, unit = numeric_values(s_curr, "salary")
    assert unit == "$"
    assert list(num) == [1250.5, 3400.0, 950.0]

    # Euro with accounting negative
    s_euro = pd.Series(["€500.00", "(€250.00)", "€1,000.00"])
    num_euro, unit_euro = numeric_values(s_euro, "net_revenue")
    assert unit_euro == "€"
    assert list(num_euro) == [500.0, -250.0, 1000.0]

    # Pure thousands commas without currency symbol
    s_commas = pd.Series(["1,250", "2,500", "10,000"])
    num_c, unit_c = numeric_values(s_commas, "headcount")
    assert unit_c is None
    assert list(num_c) == [1250.0, 2500.0, 10000.0]

    # Percentages
    s_pct = pd.Series(["18.5%", "-5.2%", "+10.0%"])
    num_p, unit_p = numeric_values(s_pct, "attrition_rate")
    assert unit_p == "%"
    assert list(num_p) == [18.5, -5.2, 10.0]


def test_insert_sheets_batching():
    import sqlite3
    import json
    from app.services.sheet_catalog import insert_sheets

    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.executescript("""
        CREATE TABLE dataset_uploads (id INTEGER PRIMARY KEY);
        CREATE TABLE sheets (id INTEGER PRIMARY KEY AUTOINCREMENT, dataset_id INTEGER, name TEXT, display_name TEXT, columns_json TEXT, profile_json TEXT, row_count INTEGER);
        CREATE TABLE sheet_rows (id INTEGER PRIMARY KEY AUTOINCREMENT, sheet_id INTEGER, row_index INTEGER, data_json TEXT);
        CREATE TABLE sheet_cells (sheet_id INTEGER, row_index INTEGER, column_name TEXT, value_key TEXT);
        CREATE TABLE tabular_chunks (id INTEGER PRIMARY KEY AUTOINCREMENT, dataset_id INTEGER, sheet_name TEXT, row_index INTEGER, chunk_text TEXT, metadata_json TEXT);
        CREATE TABLE tabular_vectors (id INTEGER PRIMARY KEY, embedding BLOB);
    """)

    conn.execute("INSERT INTO dataset_uploads (id) VALUES (1)")
    # Generate 1500 records to cross the 1000-row batch boundary
    records = [{"id": f"ID_{i}", "val": i * 10, "tag": f"T_{i % 5}"} for i in range(1500)]
    columns = ["id", "val", "tag"]
    profiles = [{"column": c} for c in columns]
    chunks = [f"Row {i}" for i in range(1500)]

    prepared = [{
        "name": "BigSheet",
        "columns": columns,
        "profiles": profiles,
        "records": records,
        "chunks": chunks,
        "vectors": []
    }]

    insert_sheets(conn, dataset_id=1, prepared=prepared, display_name="Big Sheet")

    row_count = conn.execute("SELECT COUNT(*) FROM sheet_rows").fetchone()[0]
    assert row_count == 1500

    cell_count = conn.execute("SELECT COUNT(*) FROM sheet_cells").fetchone()[0]
    assert cell_count == 4500  # 1500 rows * 3 non-empty columns

    chunk_count = conn.execute("SELECT COUNT(*) FROM tabular_chunks").fetchone()[0]
    assert chunk_count == 1500

