"""PowerPoint export and layout rendering package."""

from .pptx_styles import (
    C_BG,
    C_CARD,
    C_CARD_BORDER,
    C_BRAND,
    C_ACCENT,
    C_TEXT_LIGHT,
    C_TEXT_MUTED,
    C_SUCCESS,
    C_DANGER,
    ChartExportError,
    hex_to_rgb,
    add_styled_text_runs,
    set_slide_background,
    add_header,
    _save_deck,
    _render_footer,
)
from .pptx_charts import _add_native_chart_shape, _render_native_9box_matrix
from .pptx_layouts import (
    _render_title_hero_slide,
    _render_kpi_summary_slide,
    _render_chart_narrative_slide,
    _render_comparison_split_slide,
    _render_table_detail_slide,
    _render_full_chart_takeaway_slide,
    _render_two_charts_slide,
    _render_action_plan_slide,
    _render_generic_slide,
    _table_slide,
)

__all__ = [
    "C_BG",
    "C_CARD",
    "C_CARD_BORDER",
    "C_BRAND",
    "C_ACCENT",
    "C_TEXT_LIGHT",
    "C_TEXT_MUTED",
    "C_SUCCESS",
    "C_DANGER",
    "ChartExportError",
    "hex_to_rgb",
    "add_styled_text_runs",
    "set_slide_background",
    "add_header",
    "_save_deck",
    "_render_footer",
    "_add_native_chart_shape",
    "_render_native_9box_matrix",
    "_render_title_hero_slide",
    "_render_kpi_summary_slide",
    "_render_chart_narrative_slide",
    "_render_comparison_split_slide",
    "_render_table_detail_slide",
    "_render_full_chart_takeaway_slide",
    "_render_two_charts_slide",
    "_render_action_plan_slide",
    "_render_generic_slide",
    "_table_slide",
]
