// Self-contained briefing; source cell text is escaped, never interpreted as HTML.
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => value == null ? 'Unavailable' : Number(value).toLocaleString('en', {maximumFractionDigits:2});
export function decisionBriefHtml(data) {
  const slides = data.findings.map((f,i) => {
    const groups=f.detail.groups || [];
    const extent=Math.max(1,...groups.map(g=>Math.abs(g.value || 0)));
    const chart=groups.length ? `<div class="bars">${groups.map(g=>`<div class="row"><span>${escape(g.group)}</span><div class="track"><i style="width:${Math.abs(g.value || 0)/extent*100}%"></i><b>${number(g.value)}</b></div><small>${g.used_rows} valid records${g.small_sample?' · small group':''}</small></div>`).join('')}</div>` : `<h2>What this means</h2><p>${escape(f.implication)}</p>`;
    return `<section class="slide" id="finding-${i+1}"><div class="eyebrow">${escape(f.kind)} · ${i+1} / ${data.findings.length}</div><h1>${escape(f.title)}</h1><p class="stat">${escape(f.observation)}</p><div class="grid"><div>${chart}<p class="note">${escape(f.method)}</p></div><aside><div class="eyebrow">Proposed next step</div><h2>${escape(f.action)}</h2><p>${escape(f.owner)} · next operating review</p><hr/><p>${escape(f.implication)}</p></aside></div><footer>${escape(f.source.file)} / ${escape(f.source.sheet)} · ${escape(f.id)} · Snapshot ${escape(data.snapshot)}</footer><nav>${i?`<a href="#finding-${i}">← Previous</a>`:'<span></span>'}${i<data.findings.length-1?`<a href="#finding-${i+2}">Next →</a>`:'<a href="#methods">Coverage & definitions →</a>'}</nav></section>`;
  }).join('');
  const boundaries=data.profiles.map(p=>`<h2>${escape(p.source.file)} / ${escape(p.source.sheet)}</h2><ul>${p.limitations.map(l=>`<li>${escape(l)}</li>`).join('')}</ul>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Executive decision brief</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#0b1421;color:#e8eef8;font:16px/1.6 system-ui,sans-serif}.slide{max-width:1440px;min-height:100vh;margin:auto;padding:5vw;break-after:page}.eyebrow{color:#78dbc0;font-size:12px;text-transform:uppercase;letter-spacing:2px}h1{font-size:clamp(28px,3.7vw,54px);line-height:1.15;max-width:1100px;margin:20px 0 26px}h2{font-size:22px;line-height:1.45}.stat{font-size:clamp(18px,2vw,29px);color:#a6edda;max-width:1050px}.grid{display:grid;grid-template-columns:1.3fr 1fr;gap:40px;margin:36px 0}aside{padding:28px;border:1px solid #ffffff25;border-radius:16px;background:#162335}aside p,.note{color:#a9bbd0}.note,footer{font-size:12px}footer{border-top:1px solid #ffffff25;padding-top:18px;color:#94a9c2;overflow-wrap:anywhere}.row{display:grid;grid-template-columns:40% 1fr;gap:4px 15px;padding:9px 0;font-size:13px;break-inside:avoid}.row small{grid-column:2;color:#94a9c2}.track{height:25px;position:relative}.track i{position:absolute;left:0;height:100%;background:#367e70;border-radius:3px}.track b{position:relative;padding:3px 6px}.row span{overflow-wrap:anywhere}nav{display:flex;justify-content:space-between;margin-top:20px}a{color:#89e0c6}hr{border:0;border-top:1px solid #ffffff25;margin:24px 0}#methods{padding:5vw;max-width:1440px;margin:auto}#methods li{margin-bottom:12px}@media(max-width:700px){.grid{grid-template-columns:1fr;gap:18px}.slide{padding:24px 18px}h1{font-size:30px}}@media print{@page{size:A4 landscape;margin:12mm}body{background:white;color:#18283b}.slide{min-height:0;padding:0}h1{font-size:28px}.stat{font-size:19px;color:#1b6655}.grid{gap:24px;margin:18px 0}aside{background:#eef5f3;border-color:#b9c9c3;padding:16px}aside p,.note,footer{color:#42566c}.eyebrow{color:#1b6655}nav{display:none}.row{font-size:10px;padding:4px 0}.track{height:18px}.track i{print-color-adjust:exact}.track b{color:#18283b}h2{font-size:17px}.slide p{font-size:13px}#methods{padding:0}}
</style></head><body>${slides}<section id="methods"><div class="eyebrow">Evidence boundaries</div><h1>What these findings establish</h1><p>${escape(data.prioritization)} ${escape(data.ai_status)}</p>${boundaries}</section></body></html>`;
}
