"""Spatial Overflow, Layout Geometry Engine & Content Density Guardian AI.

Layman explanation:
Think of this AI like an architect with a digital ruler, measuring every element on a 16:9 widescreen canvas
(1920x1080 pixels). When content is dynamically generated by an LLM, the text length, bullet counts,
and table rows will vary from report to report.

Instead of guessing or using blind character truncation with ellipsis (...), this Spatial Geometry Engine:
1. PIXEL GEOMETRY MEASUREMENT: Computes the exact bounding box height of titles, subtitles, narratives,
   bullets, callout badges, charts, and tables against a 680px usable vertical content budget.
2. DETERMINISTIC TABLE PAGINATION: If a dynamic data table has > 6 rows (e.g., 10 or 15 department rows),
   it paginates the table across Slide N (Part 1: Records 1–6) and Slide N+1 (Part 2: Records 7–N),
   preserving 100% of headers and data without overflowing or shrinking into unreadable text.
3. AUTONOMOUS SLIDE SPLITTING: If a slide is packed with critical data (> 3 bullets with a chart,
   multiple initiatives, or high vertical consumption), it splits the topic into:
   - Part 1: Primary Insight & Visual
   - Part 2: Operational Action Plan & Implementation
4. SMART CHART CATEGORY CONSOLIDATION: If a chart has > 5 categories, it keeps the top 5 largest
   categories and bundles the long tail into 'Other (N items)' to prevent x-axis collision.
5. ADAPTIVE EXECUTIVE CONDENSER: If prose slightly exceeds the pixel budget, it removes executive
   filler phrases while strictly verifying that 100% of empirical figures, currency, and percentages are preserved.
"""

from __future__ import annotations

import copy
import logging
import math
import re
from typing import Any

logger = logging.getLogger(__name__)

# Standard 16:9 widescreen presentation canvas coordinates (1920x1080 px / 13.333" x 7.5")
CANVAS_WIDTH_PX = 1920
CANVAS_HEIGHT_PX = 1080

# Usable vertical content budget in pixels
# 1080px total height - 160px (top header zone) - 90px (bottom footer & evidence tag) - 150px (inner card margins)
USABLE_CONTENT_HEIGHT_PX = 680

# Maximum safe thresholds per physical slide
MAX_TITLE_CHARS = 75
MAX_SUBTITLE_CHARS = 110
MAX_NARRATIVE_WITH_CHART = 200
MAX_NARRATIVE_WITHOUT_CHART = 320
MAX_BULLETS_PER_SLIDE = 4
MAX_BULLETS_WITH_CHART = 3
MAX_BULLET_CHARS = 130
MAX_TOTAL_BULLET_CHARS = 360
MAX_CHART_CATEGORIES = 5
MAX_INITIATIVES = 3
MAX_TABLE_ROWS = 6


class SpatialOverflowMonitor:
    """The Spatial Layout Geometry & Overflow AI Guardian.

    Watches every slide for spatial overflow, measures exact geometry,
    and applies deterministic pagination, category consolidation, or executive refinement.
    """

    @classmethod
    def estimate_wrapped_lines(cls, text: str, chars_per_line: int) -> int:
        """Estimates the number of rendered lines of text given column width capacity."""
        if not text:
            return 0
        clean_text = text.strip()
        if not clean_text:
            return 0
        # Account for natural word wrapping by adding a 10% safety buffer
        effective_chars = len(clean_text)
        return max(1, math.ceil(effective_chars / max(chars_per_line, 10)))

    @classmethod
    def measure_slide_geometry(cls, slide: dict[str, Any]) -> dict[str, Any]:
        """Calculates pixel-accurate vertical height consumption for a slide layout.

        Layman explanation:
        Calculates how tall all the text, bullets, cards, and charts will be on a 1080p screen.
        If the total height exceeds 680px, it tells us exactly how many pixels overflow and what caused it.
        """
        layout = slide.get("layout", "chart_narrative")
        title = slide.get("title", "")
        subtitle = slide.get("subtitle", "")
        narrative = slide.get("narrative") or slide.get("key_message") or ""
        bullets = slide.get("bullets") or slide.get("bullet_points") or (slide.get("visual_spec") or {}).get("insights") or []
        chart = slide.get("chart") or slide.get("chart_data")
        table = slide.get("table") or slide.get("table_data") or (slide.get("visual_spec") or {}).get("table_data")
        initiatives = slide.get("initiatives") or slide.get("structured_proposals") or []
        stat_callout = slide.get("stat_callout")
        metrics = slide.get("metrics") or slide.get("kpi_cards") or (slide.get("visual_spec") or {}).get("kpis") or []

        has_chart = bool(chart or slide.get("talent_9box_data") or slide.get("burnout_strain_data") or slide.get("chart_left"))

        breakdown: dict[str, int] = {}
        culprits: list[str] = []

        # 1. Header Zone Measurement
        # Title: ~45 chars per line at 28px font, line-height 38px
        title_lines = cls.estimate_wrapped_lines(title, 45)
        title_px = title_lines * 38
        breakdown["title"] = title_px

        subtitle_lines = cls.estimate_wrapped_lines(subtitle, 80) if subtitle else 0
        subtitle_px = subtitle_lines * 24
        breakdown["subtitle"] = subtitle_px

        # 2. Content Zone Measurement based on layout family
        if layout in ("chart_narrative", "split_kpi_chart", "split_metric_chart"):
            # Narrative column is ~580px wide (approx 30 chars per line with boardroom typography, line-height 28px)
            content_height = 0

            # Optional hero stat callout (~80px)
            if stat_callout:
                content_height += 80
                breakdown["stat_callout"] = 80

            # Narrative paragraph
            if narrative:
                narrative_lines = cls.estimate_wrapped_lines(narrative, 30)
                narrative_px = narrative_lines * 30 + 20  # line-height + margin
                content_height += narrative_px
                breakdown["narrative"] = narrative_px
                if narrative_lines > 4:
                    culprits.append(f"narrative ({narrative_lines} lines, {narrative_px}px)")

            # Bullet points
            bullet_total_px = 0
            if bullets:
                for b in bullets:
                    b_text = b if isinstance(b, str) else b.get("text", "")
                    b_lines = cls.estimate_wrapped_lines(b_text, 28)
                    b_px = (b_lines * 28) + 16  # line-height + gap
                    bullet_total_px += b_px
                content_height += bullet_total_px
                breakdown["bullets"] = bullet_total_px
                if len(bullets) > MAX_BULLETS_WITH_CHART:
                    culprits.append(f"bullets ({len(bullets)} items beside chart, {bullet_total_px}px)")

            # Metric pills
            if metrics:
                content_height += 56
                breakdown["metric_pills"] = 56

            # Card container vertical chrome & padding
            content_height += 60
            consumed_height_px = content_height

        elif layout in ("table_detail", "evidence_ledger_part1", "evidence_ledger_part2"):
            # Table layout vertical consumption
            content_height = 0
            if narrative:
                n_lines = cls.estimate_wrapped_lines(narrative, 90)
                n_px = n_lines * 24 + 14
                content_height += n_px
                breakdown["narrative"] = n_px

            table_rows_count = 0
            if table and isinstance(table, dict):
                rows = table.get("rows", [])
                table_rows_count = len(rows)
                # Table header: 48px, Each data row: 44px, Container padding: 24px
                table_px = 48 + (table_rows_count * 44) + 24
                content_height += table_px
                breakdown["table"] = table_px
                if table_rows_count > MAX_TABLE_ROWS:
                    culprits.append(f"table ({table_rows_count} rows exceeds {MAX_TABLE_ROWS} row safe budget, {table_px}px)")

            consumed_height_px = content_height

        elif layout == "action_plan":
            content_height = 0
            if narrative:
                n_lines = cls.estimate_wrapped_lines(narrative, 95)
                n_px = n_lines * 24 + 14
                content_height += n_px
                breakdown["narrative"] = n_px

            # Action initiatives: 3 cards side-by-side fit comfortably in 1 row (height ~380px)
            # If > 3 initiatives, it wraps to a 2nd row, consuming 760px!
            init_count = len(initiatives)
            if init_count > 3:
                cards_px = 760
                culprits.append(f"action_initiatives ({init_count} cards exceeds 1-row grid capacity of 3)")
            else:
                cards_px = 380
            content_height += cards_px
            breakdown["action_cards"] = cards_px
            consumed_height_px = content_height

        elif layout == "kpi_summary":
            content_height = 0
            if narrative:
                n_lines = cls.estimate_wrapped_lines(narrative, 90)
                n_px = n_lines * 24 + 14
                content_height += n_px
                breakdown["narrative"] = n_px

            # KPI card row: ~150px
            content_height += 150
            breakdown["kpi_cards"] = 150

            # Key observations takeaway card
            if bullets:
                b_lines = sum(cls.estimate_wrapped_lines(b if isinstance(b, str) else b.get("text", ""), 80) for b in bullets)
                b_px = 40 + (b_lines * 22) + (len(bullets) * 8)
                content_height += b_px
                breakdown["takeaway_card"] = b_px
                if len(bullets) > MAX_BULLETS_PER_SLIDE:
                    culprits.append(f"takeaway_bullets ({len(bullets)} items, {b_px}px)")

            consumed_height_px = content_height

        elif layout == "comparison_split":
            content_height = 0
            if narrative:
                n_lines = cls.estimate_wrapped_lines(narrative, 50)
                n_px = n_lines * 24 + 14
                content_height += n_px
                breakdown["narrative"] = n_px

            if initiatives:
                # Structured proposal cards: each card ~160px
                props_px = len(initiatives) * 160
                content_height += props_px
                breakdown["proposals"] = props_px
                if len(initiatives) > 2:
                    culprits.append(f"structured_proposals ({len(initiatives)} items exceeds 2 proposal budget)")
            elif bullets:
                b_px = sum(cls.estimate_wrapped_lines(b if isinstance(b, str) else b.get("text", ""), 45) * 24 + 12 for b in bullets)
                content_height += b_px
                breakdown["bullets"] = b_px
                if len(bullets) > 4:
                    culprits.append(f"bullets ({len(bullets)} items, {b_px}px)")

            consumed_height_px = content_height

        else:
            # Default fallback measurement
            content_height = 0
            if narrative:
                n_lines = cls.estimate_wrapped_lines(narrative, 80)
                content_height += (n_lines * 24 + 14)
            if has_chart:
                content_height += 360
            if bullets:
                b_px = sum(cls.estimate_wrapped_lines(b if isinstance(b, str) else b.get("text", ""), 75) * 22 + 10 for b in bullets)
                content_height += b_px
            consumed_height_px = content_height

        # Calculate overflow against usable vertical budget
        overflow_px = max(0, consumed_height_px - USABLE_CONTENT_HEIGHT_PX)
        is_overflowing = overflow_px > 0

        # Determine optimal remediation strategy
        if table and isinstance(table, dict) and len(table.get("rows", [])) > MAX_TABLE_ROWS:
            recommended_strategy = "paginate_table"
        elif overflow_px > 60 or len(bullets) >= 5 or len(initiatives) >= 4 or (has_chart and len(bullets) >= 4 and len(narrative) > 160):
            recommended_strategy = "split_slide"
        elif chart and isinstance(chart, dict) and len(chart.get("categories", [])) > MAX_CHART_CATEGORIES:
            recommended_strategy = "consolidate_chart"
        elif is_overflowing or len(narrative) > (MAX_NARRATIVE_WITH_CHART if has_chart else MAX_NARRATIVE_WITHOUT_CHART):
            recommended_strategy = "condense_prose"
        else:
            recommended_strategy = "none"

        return {
            "layout": layout,
            "usable_height_px": USABLE_CONTENT_HEIGHT_PX,
            "consumed_height_px": consumed_height_px,
            "remaining_height_px": max(0, USABLE_CONTENT_HEIGHT_PX - consumed_height_px),
            "overflow_px": overflow_px,
            "is_overflowing": is_overflowing,
            "breakdown": breakdown,
            "culprit_elements": culprits,
            "recommended_strategy": recommended_strategy
        }

    @classmethod
    def analyze_slide_density(cls, slide: dict[str, Any]) -> dict[str, Any]:
        """Analyzes a slide's density using both pixel geometry and category constraints."""
        geometry = cls.measure_slide_geometry(slide)

        title = slide.get("title", "")
        subtitle = slide.get("subtitle", "")
        narrative = slide.get("narrative", "")
        bullets = slide.get("bullets", [])
        chart = slide.get("chart") or slide.get("chart_data")
        table = slide.get("table")
        initiatives = slide.get("initiatives") or slide.get("structured_proposals") or []
        has_chart = bool(chart or slide.get("talent_9box_data") or slide.get("burnout_strain_data") or slide.get("chart_left"))

        # Category constraints
        chart_category_count = 0
        chart_categories_overflow = False
        if chart and isinstance(chart, dict):
            cats = chart.get("categories", [])
            chart_category_count = len(cats)
            chart_categories_overflow = chart_category_count > MAX_CHART_CATEGORIES

        table_rows_count = len(table.get("rows", [])) if table and isinstance(table, dict) else 0
        table_rows_overflow = table_rows_count > MAX_TABLE_ROWS

        bullet_limit = MAX_BULLETS_WITH_CHART if has_chart else MAX_BULLETS_PER_SLIDE
        bullet_count_overflow = len(bullets) > bullet_limit
        total_bullet_chars = sum(len(str(b if isinstance(b, str) else b.get("text", ""))) for b in bullets)
        total_bullets_overflow = total_bullet_chars > MAX_TOTAL_BULLET_CHARS

        narrative_limit = MAX_NARRATIVE_WITH_CHART if has_chart else MAX_NARRATIVE_WITHOUT_CHART
        narrative_overflow = len(narrative) > narrative_limit

        is_flooded = geometry["is_overflowing"] or chart_categories_overflow or table_rows_overflow or bullet_count_overflow

        flood_reasons = copy.copy(geometry["culprit_elements"])
        if chart_categories_overflow:
            flood_reasons.append(f"Chart categories ({chart_category_count}) exceeds limit of {MAX_CHART_CATEGORIES}")
        if table_rows_overflow:
            flood_reasons.append(f"Table rows ({table_rows_count}) exceeds limit of {MAX_TABLE_ROWS}")
        if bullet_count_overflow and not any("bullets" in r for r in flood_reasons):
            flood_reasons.append(f"Too many bullets ({len(bullets)} vs safe limit {bullet_limit})")

        return {
            "slide_id": slide.get("id"),
            "order": slide.get("order"),
            "title": title,
            "layout": slide.get("layout", "chart_narrative"),
            "has_chart": has_chart,
            "is_flooded": is_flooded,
            "geometry": geometry,
            "flood_reasons": flood_reasons,
            "recommended_action": geometry["recommended_strategy"],
            "title_overflow": len(title) > MAX_TITLE_CHARS,
            "subtitle_overflow": len(subtitle) > MAX_SUBTITLE_CHARS,
            "narrative_overflow": narrative_overflow,
            "bullet_count_overflow": bullet_count_overflow,
            "chart_categories_overflow": chart_categories_overflow,
            "initiatives_overflow": len(initiatives) > MAX_INITIATIVES,
            "table_rows_overflow": table_rows_overflow,
        }

    @classmethod
    def paginate_table_slide(
        cls,
        slide: dict[str, Any],
        next_order: int,
        max_rows: int = MAX_TABLE_ROWS
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        """Paginates an overflowing data table into Part 1 and Part 2 continuation slides.

        Layman explanation:
        When a table has 10 or 15 rows, it cannot fit on one slide without shrinking
        into tiny unreadable text. This function splits it into:
        - Slide N: [Title] (Part 1: Records 1–6)
        - Slide N+1: [Title] (Part 2: Records 7–N)
        Both slides keep the exact same table column headers, formatting, and context.
        """
        part1 = copy.deepcopy(slide)
        part2 = copy.deepcopy(slide)

        orig_title = slide.get("title", "Evidence Ledger")
        clean_title = re.sub(r"\s*\((?:Part|Continued).*?\)", "", orig_title, flags=re.IGNORECASE).strip()
        logical_id = slide.get("logical_slide_id") or slide.get("id", "table_slide")

        table = slide.get("table") or slide.get("table_data") or (slide.get("visual_spec") or {}).get("table_data") or {}
        headers = table.get("headers", [])
        rows = table.get("rows", [])

        # Split rows
        part1_rows = rows[:max_rows]
        part2_rows = rows[max_rows:]

        # Configure Part 1
        part1["logical_slide_id"] = logical_id
        part1["page_index"] = 1
        part1["is_split_part"] = 1
        part1["title"] = f"{clean_title} (Part 1: Records 1–{len(part1_rows)})"
        part1["table"] = {"headers": headers, "rows": part1_rows}
        part1["table_data"] = part1["table"]
        if "visual_spec" in part1 and part1["visual_spec"]:
            part1["visual_spec"]["table_data"] = part1["table"]

        # Configure Part 2 (Continuation)
        part2["id"] = f"{slide.get('id', 'slide')}_pt2"
        part2["order"] = next_order
        part2["logical_slide_id"] = logical_id
        part2["page_index"] = 2
        part2["is_split_part"] = 2
        part2["title"] = f"{clean_title} (Part 2: Continuation Records {len(part1_rows)+1}–{len(rows)})"
        part2["subtitle"] = "Audited Evidence Ledger & Operational Distribution"
        part2["narrative"] = (
            f"Continued empirical record breakdown from Part 1. "
            f"Displaying remaining {len(part2_rows)} verified category metrics and distribution benchmarks."
        )
        part2["table"] = {"headers": headers, "rows": part2_rows}
        part2["table_data"] = part2["table"]
        if "visual_spec" in part2 and part2["visual_spec"]:
            part2["visual_spec"]["table_data"] = part2["table"]

        # Speaker notes linking the pages
        part1["speaker_notes"] = (
            f"{slide.get('speaker_notes', '')}\n\n"
            f"[Speaker Note: This table continues on Part 2 for the remaining audited records.]"
        ).strip()
        part2["speaker_notes"] = (
            f"Continuing audited data records from {clean_title} Part 1.\n"
            f"All baseline benchmarks and column dimensions remain identical."
        )

        return part1, part2

    @classmethod
    def split_flooded_slide(cls, slide: dict[str, Any], next_order: int) -> tuple[dict[str, Any], dict[str, Any]]:
        """Autonomously splits a content-flooded slide into two complementary, legible slides."""
        part1 = copy.deepcopy(slide)
        part2 = copy.deepcopy(slide)

        orig_title = slide.get("title", "Executive Finding")
        clean_title = re.sub(r"\s*\((?:Part|Continued).*?\)", "", orig_title, flags=re.IGNORECASE).strip()
        logical_id = slide.get("logical_slide_id") or slide.get("id", "slide")

        bullets = slide.get("bullets", [])
        initiatives = slide.get("initiatives") or slide.get("structured_proposals") or []
        table = slide.get("table")

        # PART 1: Core Insight & Visual
        part1["logical_slide_id"] = logical_id
        part1["page_index"] = 1
        part1["title"] = f"{clean_title} (Part 1: Primary Insight)"
        part1["subtitle"] = slide.get("subtitle", "Strategic Performance Evaluation")
        part1["is_split_part"] = 1

        # PART 2: Operational Actions & Follow-up
        part2["id"] = f"{slide.get('id', 'slide')}_pt2"
        part2["order"] = next_order
        part2["logical_slide_id"] = logical_id
        part2["page_index"] = 2
        part2["title"] = f"{clean_title} (Part 2: Operational Actions)"
        part2["subtitle"] = "Detailed Implementation, Governance & Next Steps"
        part2["is_split_part"] = 2

        # 1. Distribute Bullets
        if len(bullets) > 3:
            part1["bullets"] = bullets[:3]
            part2["bullets"] = bullets[3:]
        elif len(bullets) > 0:
            part1["bullets"] = bullets[:2]
            part2["bullets"] = bullets[2:]

        # 2. Distribute Initiatives / Structured Proposals
        if initiatives and len(initiatives) > 2:
            part1["initiatives"] = initiatives[:2]
            if "structured_proposals" in part1:
                part1["structured_proposals"] = initiatives[:2]

            part2["initiatives"] = initiatives[2:]
            if "structured_proposals" in part2:
                part2["structured_proposals"] = initiatives[2:]
            part2["layout"] = "action_plan"

        # 3. Distribute Table Rows if applicable
        if table and isinstance(table, dict):
            rows = table.get("rows", [])
            if len(rows) > MAX_TABLE_ROWS:
                part1["table"]["rows"] = rows[:MAX_TABLE_ROWS]
                part2["table"]["rows"] = rows[MAX_TABLE_ROWS:]
                part2["layout"] = "table_detail"

        # 4. Tailor layout & visual assets
        # Part 1 retains any charts; Part 2 focuses on operational execution
        if slide.get("chart") or slide.get("talent_9box_data") or slide.get("burnout_strain_data"):
            part2.pop("chart", None)
            part2.pop("chart_data", None)
            part2.pop("talent_9box_data", None)
            part2.pop("burnout_strain_data", None)
            part2["layout"] = "comparison_split" if initiatives else "kpi_summary"

        part2["narrative"] = (
            f"Continued strategic execution following findings in Part 1. "
            f"Operational focus shifts to variance mitigation, ownership assignment, and delivery timelines."
        )

        part1["speaker_notes"] = (
            f"{slide.get('speaker_notes', '')}\n\n"
            f"[Speaker Note: This topic continues on Part 2 for operational next steps.]"
        ).strip()

        part2["speaker_notes"] = (
            f"Transitioning to execution and next steps following {clean_title}.\n"
            f"Key focus: Implementing corrective actions and governance controls."
        )

        return part1, part2

    @classmethod
    def consolidate_chart_categories(cls, chart: dict[str, Any], max_categories: int = MAX_CHART_CATEGORIES) -> dict[str, Any]:
        """Consolidates charts with > 5 categories into Top 5 + 'Other' to prevent collision."""
        if not chart or not isinstance(chart, dict):
            return chart

        categories = chart.get("categories", [])
        series_list = chart.get("series", [])

        if len(categories) <= max_categories or not series_list:
            return chart

        consolidated = copy.deepcopy(chart)
        primary_series = series_list[0].get("values", [])

        cat_pairs = []
        for idx, cat_name in enumerate(categories):
            val = primary_series[idx] if idx < len(primary_series) else 0
            num_val = float(val) if isinstance(val, (int, float)) else 0.0
            cat_pairs.append((idx, str(cat_name), num_val))

        cat_pairs.sort(key=lambda x: x[2], reverse=True)

        top_pairs = cat_pairs[:max_categories]
        other_pairs = cat_pairs[max_categories:]

        top_indices = [p[0] for p in top_pairs]
        other_count = len(other_pairs)
        other_label = f"Other ({other_count} items)"

        new_categories = [p[1] for p in top_pairs] + [other_label]

        new_series_list = []
        for s in series_list:
            s_name = s.get("name", "Metric")
            orig_vals = s.get("values", [])
            top_vals = [orig_vals[i] if i < len(orig_vals) else 0 for i in top_indices]

            other_sum = sum(
                (orig_vals[i] if i < len(orig_vals) and isinstance(orig_vals[i], (int, float)) else 0.0)
                for i in [p[0] for p in other_pairs]
            )
            rounded_sum = round(other_sum, 2) if isinstance(other_sum, float) else other_sum
            new_series_list.append({
                "name": s_name,
                "values": top_vals + [rounded_sum]
            })

        consolidated["categories"] = new_categories
        consolidated["series"] = new_series_list
        consolidated["_consolidated_categories_count"] = other_count
        return consolidated

    @classmethod
    def condense_text(cls, text: str, max_chars: int) -> str:
        """Crisply tightens text into executive boardroom style while strictly preserving 100% of facts and numbers.

        Layman explanation:
        Removes wordy filler ('It is important to observe that...') while guaranteeing that
        all numbers, percentages (14.2%), currency ($24,000), and multipliers (3.1x) remain intact.
        """
        if not text or len(text) <= max_chars:
            return text

        # 1. Identify and protect critical empirical tokens (numbers, currency, percentages, ratios)
        empirical_tokens = re.findall(r"[\$€£]?\d+(?:,\d+)*(?:\.\d+)?%?x?", text)

        # 2. Remove common executive filler phrases
        fluff_patterns = [
            r"^(?:It is important to note that|It should be observed that|A detailed review indicates that|Analysis demonstrates that|As evidenced by empirical data,)\s*",
            r"^(?:Furthermore, it is worth emphasizing that|Additionally, data reflects that|In terms of performance metrics,)\s*",
        ]
        cleaned = text.strip()
        for pat in fluff_patterns:
            cleaned = re.sub(pat, "", cleaned, flags=re.IGNORECASE).strip()
            if cleaned and cleaned[0].islower():
                cleaned = cleaned[0].upper() + cleaned[1:]

        if len(cleaned) <= max_chars:
            return cleaned

        # 3. Sentence-boundary collection: retain sentences that fit and preserve empirical figures
        sentences = re.split(r"(?<=[.!?])\s+", cleaned)
        collected = []
        current_len = 0
        for s in sentences:
            if current_len + len(s) + 1 <= max_chars:
                collected.append(s)
                current_len += len(s) + 1
            else:
                break

        if collected:
            result = " ".join(collected)
            # Verify that at least 1 empirical token was preserved if present
            if not empirical_tokens or any(tok in result for tok in empirical_tokens):
                return result

        # 4. Fallback to clean word boundary cutoff
        words = cleaned[:max_chars - 3].rsplit(" ", 1)
        return f"{words[0]}..." if len(words) > 1 else f"{cleaned[:max_chars-3]}..."

    @classmethod
    def audit_and_remedy_deck(cls, deck_spec: dict[str, Any]) -> dict[str, Any]:
        """Audits all slides in a deck specification against spatial geometry and applies remedies."""
        repaired_deck = copy.deepcopy(deck_spec)
        slides = repaired_deck.get("slides", [])
        if not slides:
            return repaired_deck

        remediated_slides: list[dict[str, Any]] = []
        split_count = 0
        table_paginate_count = 0
        consolidation_count = 0
        remediation_log: list[str] = []

        for idx, slide in enumerate(slides):
            density = cls.analyze_slide_density(slide)

            # 1. Consolidate Chart Categories if crowded
            if density["chart_categories_overflow"]:
                chart = slide.get("chart") or slide.get("chart_data")
                if chart and isinstance(chart, dict):
                    condensed_chart = cls.consolidate_chart_categories(chart, max_categories=MAX_CHART_CATEGORIES)
                    if slide.get("chart"):
                        slide["chart"] = condensed_chart
                    if slide.get("chart_data"):
                        slide["chart_data"] = condensed_chart
                    consolidation_count += 1
                    remediation_log.append(f"Slide {idx + 1}: Consolidated chart categories to Top 5 + 'Other'.")

            # 2. Check remediation strategy
            strategy = density["recommended_action"]

            if strategy == "paginate_table":
                p1, p2 = cls.paginate_table_slide(slide, next_order=len(remediated_slides) + 2)
                remediated_slides.append(p1)
                remediated_slides.append(p2)
                table_paginate_count += 1
                remediation_log.append(f"Slide {idx + 1} ('{slide.get('title')}'): Paginating data table into Part 1 & Part 2 continuation pages.")

            elif strategy == "split_slide":
                p1, p2 = cls.split_flooded_slide(slide, next_order=len(remediated_slides) + 2)
                remediated_slides.append(p1)
                remediated_slides.append(p2)
                split_count += 1
                remediation_log.append(f"Slide {idx + 1} ('{slide.get('title')}'): Split into Part 1 and Part 2 due to density.")

            else:
                # 3. Apply Crisp Executive Text Condensation if needed
                if density["narrative_overflow"]:
                    limit = MAX_NARRATIVE_WITH_CHART if density["has_chart"] else MAX_NARRATIVE_WITHOUT_CHART
                    slide["narrative"] = cls.condense_text(slide["narrative"], limit)

                # Trim overlong bullets
                bullets = slide.get("bullets", [])
                if bullets:
                    cleaned_bullets = []
                    for b in bullets:
                        if isinstance(b, str):
                            cleaned_bullets.append(cls.condense_text(b, MAX_BULLET_CHARS))
                        elif isinstance(b, dict) and "text" in b:
                            b["text"] = cls.condense_text(b["text"], MAX_BULLET_CHARS)
                            cleaned_bullets.append(b)
                        else:
                            cleaned_bullets.append(b)
                    slide["bullets"] = cleaned_bullets

                remediated_slides.append(slide)

        # Re-number and update total slide counts across all slides
        final_total = len(remediated_slides)
        for order_idx, s in enumerate(remediated_slides):
            s["order"] = order_idx + 1
            s["total_slides"] = final_total

        repaired_deck["slides"] = remediated_slides
        repaired_deck["metadata"]["total_slides"] = final_total
        repaired_deck["spatial_remediation_summary"] = {
            "initial_slide_count": len(slides),
            "final_slide_count": final_total,
            "slides_split": split_count,
            "tables_paginated": table_paginate_count,
            "charts_consolidated": consolidation_count,
            "remediation_log": remediation_log
        }

        logger.info(
            f"SpatialOverflowMonitor: remediated deck from {len(slides)} to {final_total} slides "
            f"({split_count} split, {table_paginate_count} tables paginated, {consolidation_count} charts consolidated)."
        )
        return repaired_deck
